FREE SHOWPROGRESS
OPEN/CLOSE 'EastDoverSWI.BAS.ibound1' 1 (FREE) -1
OPEN/CLOSE 'EastDoverSWI.BAS.ibound2' 1 (FREE) -1
OPEN/CLOSE 'EastDoverSWI.BAS.ibound3' 1 (FREE) -1
OPEN/CLOSE 'EastDoverSWI.BAS.ibound4' 1 (FREE) -1
1E+30
OPEN/CLOSE 'EastDoverSWI.BAS.head1' 1 (FREE) -1  #Initial heads for layer 1
OPEN/CLOSE 'EastDoverSWI.BAS.head2' 1 (FREE) -1  #Initial heads for layer 2
OPEN/CLOSE 'EastDoverSWI.BAS.head3' 1 (FREE) -1  #Initial heads for layer 3
OPEN/CLOSE 'EastDoverSWI.BAS.head4' 1 (FREE) -1  #Initial heads for layer 4
